[package]
name = "swap-and-match-engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enumset = { version = "1.0.7", features = ["serde"] }
primitive-types = { version = "0.10.1", features = ["serde"] }
serde = { version = "1.0.129", features = ["derive"] }